In [ ]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv((r"E:\faranishath\Fish.csv"))

In [4]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [6]:
x=dataset.iloc[:,0:6].values
x

array([['Bream', 242.0, 23.2, 25.4, 30.0, 11.52],
       ['Bream', 290.0, 24.0, 26.3, 31.2, 12.48],
       ['Bream', 340.0, 23.9, 26.5, 31.1, 12.3778],
       ['Bream', 363.0, 26.3, 29.0, 33.5, 12.73],
       ['Bream', 430.0, 26.5, 29.0, 34.0, 12.444],
       ['Bream', 450.0, 26.8, 29.7, 34.7, 13.6024],
       ['Bream', 500.0, 26.8, 29.7, 34.5, 14.1795],
       ['Bream', 390.0, 27.6, 30.0, 35.0, 12.67],
       ['Bream', 450.0, 27.6, 30.0, 35.1, 14.0049],
       ['Bream', 500.0, 28.5, 30.7, 36.2, 14.2266],
       ['Bream', 475.0, 28.4, 31.0, 36.2, 14.2628],
       ['Bream', 500.0, 28.7, 31.0, 36.2, 14.3714],
       ['Bream', 500.0, 29.1, 31.5, 36.4, 13.7592],
       ['Bream', 340.0, 29.5, 32.0, 37.3, 13.9129],
       ['Bream', 600.0, 29.4, 32.0, 37.2, 14.9544],
       ['Bream', 600.0, 29.4, 32.0, 37.2, 15.437999999999999],
       ['Bream', 700.0, 30.4, 33.0, 38.3, 14.8604],
       ['Bream', 700.0, 30.4, 33.0, 38.5, 14.937999999999999],
       ['Bream', 610.0, 30.9, 33.5, 38.6, 15.633],


In [7]:
y=dataset.iloc[:,6].values
y

array([4.02  , 4.3056, 4.6961, 4.4555, 5.134 , 4.9274, 5.2785, 4.69  ,
       4.8438, 4.9594, 5.1042, 4.8146, 4.368 , 5.0728, 5.1708, 5.58  ,
       5.2854, 5.1975, 5.1338, 5.7276, 5.5695, 5.3704, 5.2801, 6.1306,
       5.589 , 6.0532, 6.09  , 5.8515, 6.1984, 6.603 , 6.3063, 6.292 ,
       6.7497, 6.7473, 6.3705, 2.268 , 2.8217, 2.9044, 3.1746, 3.5742,
       3.3516, 3.3957, 3.2943, 3.7544, 3.5478, 3.8203, 3.325 , 3.8   ,
       3.8352, 3.6312, 4.1272, 3.906 , 4.4968, 4.7736, 5.355 , 4.2476,
       4.2485, 4.6816, 6.562 , 6.5736, 6.525 , 2.3265, 2.3142, 2.673 ,
       2.9181, 3.2928, 3.2944, 3.4104, 3.1571, 3.6636, 4.144 , 4.234 ,
       1.408 , 1.9992, 2.432 , 2.6316, 2.9415, 3.3216, 3.1234, 3.0502,
       3.0368, 2.772 , 3.555 , 3.3075, 3.6675, 3.534 , 3.4075, 3.525 ,
       3.525 , 3.525 , 3.995 , 3.624 , 3.624 , 3.63  , 3.626 , 3.725 ,
       3.723 , 3.825 , 4.1658, 3.6835, 4.239 , 4.144 , 5.1373, 4.335 ,
       4.335 , 4.5662, 4.2042, 4.6354, 4.7716, 6.018 , 6.3875, 7.7957,
      

In [8]:
dataset['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

In [10]:
x.shape


(159, 12)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=402)

In [12]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
ypred=mlr.predict(x_test)

In [14]:
ypred

array([7.13142424, 5.63892283, 3.21540885, 4.01556569, 4.54675664,
       7.44578013, 6.97920707, 1.46553517, 6.74993813, 3.41340213,
       1.40156641, 7.52629242, 3.6056752 , 2.51111759, 4.07603743,
       3.605811  , 6.02417474, 4.76018045, 6.37456599, 5.35471223,
       7.44622129, 5.55690554, 7.00433919, 6.77861288, 2.82896346,
       3.97256927, 4.86387137, 3.64979827, 3.54448105, 1.28578548,
       3.37598357, 4.25481941])

In [15]:
from sklearn.metrics import r2_score
acc=r2_score(ypred,y_test)

In [16]:
acc

0.975275505507994

In [17]:
mlr.predict(ct.transform(dataset.head(5)))

array([3.66368544, 4.07603743, 3.97266845, 4.25481941, 4.25341166])

In [18]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [19]:
b=ct.transform([["Bream",24,56.3,32.6,98,34]])

In [20]:
b

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 24, 56.3, 32.6, 98, 34]],
      dtype=object)

In [21]:
mlr.predict(b)

array([23.8788411])